name: 'MWAA Local Runner'
description: 'Generates an ephemeral MWAA environment within GitHub Actions'
author: 'Chris Horne'

# Define your inputs here.
inputs:
  up:
    description: 'whether to run docker-compose up'
    required: false
    default: 'false'
  down:
    description: 'whether to run docker-compose down'
    required: false
    default: 'false'
  exec:
    description: 'whether to run docker-compose exec'
    required: false
    default: 'false'
  exec-command:
    description: 'command to run in docker-compose exec'
    required: false
    default: 'airflow'
  repo-token:
    description: 'token for the repo'
    required: false

# Define your outputs here.
# outputs:

runs:
  using: composite
  steps:
    - name: Checkout aws-mwaa-local-runner
      uses: actions/checkout@v4
      with:
        repository: aws/aws-mwaa-local-runner
        path: aws-mwaa-local-runner

    - name: Log in to GHCR
      if: inputs.up == 'true'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.repo-token }}

    - name: Pull docker images
      if: inputs.up == 'true'
      shell: bash
      run: |
        docker pull ghcr.io/phaelin/mwaa-local-runner-action:main
        docker tag phaelin/mwaa-local-runner-action:main amazon/mwaa-local:2_7

    - name: Run docker-compose up
      if: inputs.up == 'true'
      shell: bash
      working-directory: aws-mwaa-local-runner/docker/
      run: docker-compose -f ./docker-compose-local.yml up -d

    - name: Run docker-compose down
      if: inputs.down == 'true'
      shell: bash
      run: docker-compose down

    - name: Run docker-compose exec
      if: inputs.exec == 'true'
      shell: bash
      run: |
        docker-compose exec -T local-runner bash -c '${{ inputs.exec-command }}'' >> $GITHUB_STEP_SUMMARY


